
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/world-db
    username: world
    password: world123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect